---
title: "MSPMS-Shiny"
author: "Charlie Bayne"
date: "`r Sys.Date()`"
output:
  html_document:
        theme: cosmo
        highlight: tango
        df_print: paged
---

```{r setup, include=FALSE}
library(tidyverse)
ggplot2::theme_set(ggprism::theme_prism(palette = "viridis"))
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE)
```

# About 

This is a Shiny app designed to be a basic interface for the 
[mspms R package](https://github.com/baynec2/mspms) to analyze data from the 
[Multiplex Substrate Profiling by Mass Spectrometry (MSP-MS) method](https://pubmed.ncbi.nlm.nih.gov/36948708/)

On the side bar, you will also see 7 tabs: About, File Upload, Output, QC, Stats, DataViz, and Report  

## About  
The About tab links to the instructions shown on this page. 


## File Upload
The File Upload tab is where you will upload your files. 

You must upload a design matrix file, which should be a .csv file.   

The design matrix file should be a csv file with the following columns: 
"sample", "group","condition","time". The sample column should contain the names 
of the samples as found in the PEAKS files. The group column should contain the
group that the sample belongs to. This can be any thing, as long as it is the 
same per group. The time column should contain the duration of incubation, and 
the condition column should include any experimental condition such as 
protease inhibitor.  

Depending on what upstream proteomics software you are using, you will then 
upload export files to the appropriate loader. 

### Peaks
Upload your LFQ and ID file in the indicated location. 
These should be .csv files.  


### Proteome Discoverer. 

Upload your proteome discoverer file to the indicated location. 
This should be a .xlsx file

## Peptide Library

This is a .csv file of the peptide library used. This must contain columns library_reference_id, library_match_sequence, and library_real_sequence. The library_reference_id must match what is used in your PEAKS or Proteome Discoverer files by name. 

If one is not provided, the default peptide library will be used (mspms::peptide_library)

## Output 

Output contains a rendering of the normalized data, and a button that says 
download. This button will allow you to download the data that has been 
processed as a .csv file.  

## QC

Here plots of basic QC checks are shown. 

## Stats

Stats contains a table of the results of the t-tests (for each condition 
and time relative to time 0) as well as ANOVAs testing for an effect of time.
Be patient, when it is finished running a table will appear and the data will
be ready for download.

Both of these data frames can be downloaded by using the download results

## Dataviz

The DataViz tab contains a PCA plot, heatmap of the data, volcano plots, 
icelogo, and the count of cleavages per position of all the data. Be patient,
these plots take a while to render.  

The volcano plots show the results of the t-tests relative to T0 for each 
condition. 

The ice logo shows the cleavage sequences were found to be significantly 
different (qvalue <= 0.05) and with a log2fc > 3 relative to T0 for 
any condition. 

The count of cleavages per position plot shows the count of cleavages per
position of the peptide library for peptides found to significantly different 
(qvalue <= 0.05) and with a log2fc > 3 relative to T0 for any condition. 

## Report

The report tab contains a download button that allows the user to download
a standardized .html report with a simple analysis of the data 
(facilitated by mspms::generate_report()).